name: oracle cloud deploy
on:
  push:
    branches:
      - main
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install
        working-directory: ./client
        run: yarn
      - name: build
        working-directory: ./client
        run: yarn build
        env:
          CI: true
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install
        working-directory: ./server
        run: yarn
      - name: build
        working-directory: ./server
        run: yarn build
        env:
          CI: true
  deploy:
    needs: [ build-frontend, build-backend ]
    runs-on: ubuntu-latest
    steps:
      - name: pull and update frontend with backend then restart nginx server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OC_HOST }}
          username: ${{ secrets.OC_USER }}
          key: ${{ secrets.OC_KEY }}
          port: ${{ secrets.OC_PORT }}
          script: |
            sudo -s
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/chatServer
            git pull
            cd client
            rm -rf dist
            yarn build
            cd ../server
            pm2 stop all 
            rm -rf dist
            yarn build
            cd dist
            pm2 start main.js --watch